import type { Metadata } from "next";
import "./globals.css";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <div className="p-8">
          <Suspense fallback={<>now loading</>}>
            <main>
            {children}
            </main>
          </Suspense>
        </div>
      </body>
    </html>
  );
}
